### ISSUE TITLE
rang-long 对mapFile的partitionnum检测存在问题？

### ISSUE THREAD

**Issue by guoguobo** [MyCATApache/Mycat-Server#1284]
AutoPartitionByLong中对分片的partitionnumber的检测是
	public int getPartitionNum() {
		int nPartition = longRongs.length;
		return nPartition;
	}
如上，计算的是longrongs的长度。
如果我在mapFile中写1-1000=0，1001-2000=1，2001-3000=0，3001-4000=1，1.6版本在启动检查分片表分片算法定义与分片dataNode是否匹配时。提示如下报错：
STATUS | wrapper  | 2016/12/08 11:35:27 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/12/08 11:35:27 | Launching a JVM...
INFO   | jvm 1    | 2016/12/08 11:35:27 | OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=64M; support was removed in 8.0
INFO   | jvm 1    | 2016/12/08 11:35:27 | OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
INFO   | jvm 1    | 2016/12/08 11:35:27 | OpenJDK 64-Bit Server VM warning: CMSFullGCsBeforeCompaction is deprecated and will likely be removed in a future release.
INFO   | jvm 1    | 2016/12/08 11:35:27 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2016/12/08 11:35:27 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2016/12/08 11:35:27 |
INFO   | jvm 1    | 2016/12/08 11:35:28 |
INFO   | jvm 1    | 2016/12/08 11:35:28 | WrapperSimpleApp: Encountered an error running main: java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2016/12/08 11:35:28 | java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.MycatStartup.main(MycatStartup.java:53)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/12/08 11:35:28 | Caused by: io.mycat.config.util.ConfigException: Illegal table conf : table [ APP_DEVICE_EXT ] rule function [ rang-long ] partition size : 8016 > table datanode size : 16, please make sure table datanode size = function partition size
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.checkRuleSuitTable(XMLSchemaLoader.java:563)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.loadTables(XMLSchemaLoader.java:396)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.loadSchemas(XMLSchemaLoader.java:173)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.load(XMLSchemaLoader.java:122)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:83)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:87)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.config.ConfigInitializer.<init>(ConfigInitializer.java:74)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.config.MycatConfig.<init>(MycatConfig.java:72)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.MycatServer.<init>(MycatServer.java:144)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	at io.mycat.MycatServer.<clinit>(MycatServer.java:96)
INFO   | jvm 1    | 2016/12/08 11:35:28 | 	... 7 more
STATUS | wrapper  | 2016/12/08 11:35:30 | <-- Wrapper Stopped

感觉是不是这块的计算是有问题的，自定义范围的这种分片方法应该可以写多个不连续的范围也可以才对。因为可能前期考虑不周等，需要增加范围。请问这块是不是应该计算nodeIndx的distinct才对，而不是用longrongs.length

**Comment by HashZhang** [comment]
你是如何配置的8016个分片。。。。报错提示，你配置了8016个分片，实际上有16个

**Comment by HashZhang** [comment]
你是如何配置的8016个分片。。。。报错提示，你配置了8016个分片，实际上有16个

发件人: guoguobo [mailto:notifications@github.com]
发送时间: 2016年12月9日 11:36
收件人: MyCATApache/Mycat-Server
主题: [MyCATApache/Mycat-Server] rang-long 对mapFile的partitionnum检测存在问题？ (#1284)


AutoPartitionByLong中对分片的partitionnumber的检测是
public int getPartitionNum() {
int nPartition = longRongs.length;
return nPartition;
}
如上，计算的是longrongs的长度。
如果我在mapFile中写1-1000=0，1001-2000=1，2001-3000=0，3001-4000=1，1.6版本在启动检查分片表分片算法定义与分片dataNode是否匹配时。提示如下报错：
STATUS | wrapper | 2016/12/08 11:35:27 | --> Wrapper Started as Daemon
STATUS | wrapper | 2016/12/08 11:35:27 | Launching a JVM...
INFO | jvm 1 | 2016/12/08 11:35:27 | OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=64M; support was removed in 8.0
INFO | jvm 1 | 2016/12/08 11:35:27 | OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
INFO | jvm 1 | 2016/12/08 11:35:27 | OpenJDK 64-Bit Server VM warning: CMSFullGCsBeforeCompaction is deprecated and will likely be removed in a future release.
INFO | jvm 1 | 2016/12/08 11:35:27 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO | jvm 1 | 2016/12/08 11:35:27 | Copyright 1999-2006 Tanuki Software, Inc. All Rights Reserved.
INFO | jvm 1 | 2016/12/08 11:35:27 |
INFO | jvm 1 | 2016/12/08 11:35:28 |
INFO | jvm 1 | 2016/12/08 11:35:28 | WrapperSimpleApp: Encountered an error running main: java.lang.ExceptionInInitializerError
INFO | jvm 1 | 2016/12/08 11:35:28 | java.lang.ExceptionInInitializerError
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.MycatStartup.main(MycatStartup.java:53)
INFO | jvm 1 | 2016/12/08 11:35:28 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO | jvm 1 | 2016/12/08 11:35:28 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO | jvm 1 | 2016/12/08 11:35:28 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO | jvm 1 | 2016/12/08 11:35:28 | at java.lang.reflect.Method.invoke(Method.java:498)
INFO | jvm 1 | 2016/12/08 11:35:28 | at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO | jvm 1 | 2016/12/08 11:35:28 | at java.lang.Thread.run(Thread.java:745)
INFO | jvm 1 | 2016/12/08 11:35:28 | Caused by: io.mycat.config.util.ConfigException: Illegal table conf : table [ APP_DEVICE_EXT ] rule function [ rang-long ] partition size : 8016 > table datanode size : 16, please make sure table datanode size = function partition size
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.config.loader.xml.XMLSchemaLoader.checkRuleSuitTable(XMLSchemaLoader.java:563)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.config.loader.xml.XMLSchemaLoader.loadTables(XMLSchemaLoader.java:396)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.config.loader.xml.XMLSchemaLoader.loadSchemas(XMLSchemaLoader.java:173)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.config.loader.xml.XMLSchemaLoader.load(XMLSchemaLoader.java:122)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.config.loader.xml.XMLSchemaLoader.(XMLSchemaLoader.java:83)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.config.loader.xml.XMLSchemaLoader.(XMLSchemaLoader.java:87)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.config.ConfigInitializer.(ConfigInitializer.java:74)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.config.MycatConfig.(MycatConfig.java:72)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.MycatServer.(MycatServer.java:144)
INFO | jvm 1 | 2016/12/08 11:35:28 | at io.mycat.MycatServer.(MycatServer.java:96)
INFO | jvm 1 | 2016/12/08 11:35:28 | ... 7 more
STATUS | wrapper | 2016/12/08 11:35:30 | <-- Wrapper Stopped

感觉是不是这块的计算是有问题的，自定义范围的这种分片方法应该可以写多个不连续的范围也可以才对。因为可能前期考虑不周等，需要增加范围。请问这块是不是应该计算nodeIndx的distinct才对，而不是用longrongs.length

**Comment by magicdoom** [comment]
这个是校验   按照规则时那个节点    但是你实际配置的节点数量不够

**Comment by ZzzCrazyPig** [comment]
@magicdoom  这个应该是我没考虑到这个算法还有那种配置方法，@guoguobo 他的那种配置思路是这样的:

```
0-1000=0
1001-2000=0
20001-3000=1
```

我检测的时候 partitionCount = 3 ，而我相信他的dataNode只有2个，所以这个时候就报错了。应该是我的判断有问题。@guoguobo 你是用源码debug出来的么

**Comment by ZzzCrazyPig** [comment]
@HashZhang 他那个配置方法是因为多个Range会指定到同一个dataNode，而我的判断逻辑是判断Range的size和datanode的size去比较大小。还真没考虑他那种情况。这应该是我的判断问题

**Comment by ZzzCrazyPig** [comment]
修复了`AutoPartitionLong`、`PartitionByPattern`和`PartitionByPrefixPattern` partitionNum的计算方式为distinct(nodeIndex)

**Comment by guoguobo** [comment]
@ZzzCrazyPig 我是通过报错堆栈，去读源码发现的。这块昨天我自己做了个fix，然后做了重新打包测试，目前还没未返现问题。
    @Override
    public int getPartitionNum() {
        HashSet<Integer> s = new HashSet<Integer>();
        for (int i = 0;i < longRongs.length; i++) {
            s.add(longRongs[i].nodeIndx);
        }
        int nPartition = s.size();
        return nPartition;
    }
我这边是这样做了个修复，看了下你的fix，是一致的想法。
