### ISSUE TITLE
mycat-release 1.6版本没有自带sharding-by-date规则，自己建立出错

### ISSUE THREAD

**Issue by ymjperson** [MyCATApache/Mycat-Server#1422]
系统是Ubuntu 16.04

## 我的rule.xml是这样写的
	<tableRule name="sharding-by-date">
		<rule>
			<columns>create_time</columns>
			<algorithm>partbydate</algorithm>
		</rule>
	</tableRule>

	<function name="partbydate"
		class="io.mycat.route.function.PartitionByDate">
		<property name="dateFormat">yyyyMMdd</property>
		<property name="sBeginDate">20150101</property>
		<property name="sEndDate">20150201</property>
		<property name="sPartionDay">10</property>
	</function>

## 然后是schema.xml

		<table name="testdate" primaryKey="ID" dataNode="dn1,dn2,dn3" rule="sharding-by-date" />

然后就启动不了mycat了

➜  bin ./mycat start
Starting Mycat-server...
➜  bin ./mycat status
Mycat-server is not running.

而rule.xml里面没有存在上述有关内容的时候，sharding-by-month这个分片规则是能够正常运行的

## 其rule.xml

	<tableRule name="sharding-by-month">
		<rule>
			<columns>create_time</columns>
			<algorithm>partbymonth</algorithm>
		</rule>
	</tableRule>
	<function name="partbymonth"
		class="io.mycat.route.function.PartitionByMonth">
		<property name="dateFormat">yyyyMMdd</property>
		<property name="sBeginDate">20150101</property>
	</function>

## 其schema.xml
		<table name="testmonth" primaryKey="ID" dataNode="dn1,dn2,dn3" rule="sharding-by-month" />

求解。

**Comment by ZzzCrazyPig** [comment]
看下logs目录下的日志，看一下报错日志是什么

**Comment by PersonYmj** [comment]
不好意思，才发出来，今天测了下 日志是这样的
STATUS | wrapper  | 2017/04/03 17:53:04 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2017/04/03 17:53:04 | Launching a JVM...
INFO   | jvm 1    | 2017/04/03 17:53:04 | Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=64M; support was removed in 8.0
INFO   | jvm 1    | 2017/04/03 17:53:05 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2017/04/03 17:53:05 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2017/04/03 17:53:05 | 
INFO   | jvm 1    | 2017/04/03 17:53:05 | 
INFO   | jvm 1    | 2017/04/03 17:53:05 | WrapperSimpleApp: Encountered an error running main: java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2017/04/03 17:53:05 | java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.MycatStartup.main(MycatStartup.java:53)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at java.lang.reflect.Method.invoke(Method.java:497)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/04/03 17:53:05 | Caused by: io.mycat.config.util.ConfigException: Illegal table conf : table [ TESTDATE ] rule function [ partbydate ] partition size : 4 > table datanode size : 3, please make sure table datanode size = function partition size
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.checkRuleSuitTable(XMLSchemaLoader.java:563)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.loadTables(XMLSchemaLoader.java:396)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.loadSchemas(XMLSchemaLoader.java:173)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.load(XMLSchemaLoader.java:122)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:83)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:87)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.config.ConfigInitializer.<init>(ConfigInitializer.java:74)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.config.MycatConfig.<init>(MycatConfig.java:72)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.MycatServer.<init>(MycatServer.java:144)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	at io.mycat.MycatServer.<clinit>(MycatServer.java:96)
INFO   | jvm 1    | 2017/04/03 17:53:05 | 	... 7 more
STATUS | wrapper  | 2017/04/03 17:53:08 | <-- Wrapper Stopped

**Comment by ZzzCrazyPig** [comment]
分区数量大于分片表配置的dn数量，你的dn应该是3个，但是你这个分片函数应该会分4个分片，所以报错了

**Comment by PersonYmj** [comment]
多谢！嗨呀看这个没看仔细
